// Generated by microcms-cli gen-types.
// Source: microCMS Management API (/api/v1/apis, /api/v1/apis/{endpoint}).
// Note: This command does not fetch content from microCMS Content API.
// DO NOT EDIT.

export interface MicroCMSContentId {
  id: string;
}

export interface MicroCMSDate {
  createdAt: string;
  updatedAt: string;
  publishedAt?: string;
  revisedAt?: string;
}

export interface MicroCMSImage {
  url: string;
  width?: number;
  height?: number;
  alt?: string;
}

export interface MicroCMSFile {
  url: string;
  fileSize?: number;
}

export interface MicroCMSListResponse<T> {
  contents: (T & MicroCMSListContent)[];
  totalCount: number;
  limit: number;
  offset: number;
}

export type MicroCMSListContent = MicroCMSContentId & MicroCMSDate;
export type MicroCMSObjectContent = MicroCMSDate;

// Endpoint schema from Management API: blogs (LIST)

export type BlogsSchema = {
  title?: string;
  content?: string;
  eyecatch?: MicroCMSImage;
  category?: CategoriesContent;
};

export type BlogsContent = BlogsSchema & MicroCMSListContent;
export type BlogsListResponse = MicroCMSListResponse<BlogsSchema>;

// Endpoint schema from Management API: categories (LIST)

export type CategoriesSchema = {
  name?: string;
};

export type CategoriesContent = CategoriesSchema & MicroCMSListContent;
export type CategoriesListResponse = MicroCMSListResponse<CategoriesSchema>;
